services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./docker/lavalink/application.yml:/opt/Lavalink/application.yml
      - ./docker/lavalink/plugins:/opt/Lavalink/plugins
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"

  bot:
    env_file:
      - ../prod.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-bot
    restart: unless-stopped
    depends_on:
      - lavalink
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
